/**
 * The chat layer's types — copied from the OpenAPI spec (`/docs-json`), NOT
 * inferred from the backend's DB schema. The two differ in two known places:
 *
 * - `MessageDto` has NO `deletedAt`, even though the `messages` table has that
 *   column.
 * - `ConversationDto` has NO `lastMessageAt`, even though the backend sorts by
 *   that column.
 *
 * See `docs/chat.md` §0 and §3.3.
 */

export type ConversationType = "direct" | "group";
export type MessageType = "text" | "system";

/** CLIENT-ONLY — the backend never returns this field. */
export type MessageStatus = "sending" | "sent" | "failed";

/** `MessageDto`. Required: id, conversationId, type, body, createdAt. */
export type Message = {
  /** A UUID v7 generated by the CLIENT — the basis of idempotency, see `docs/chat.md` §4. */
  id: string;
  conversationId: string;
  /** null once the sender is deleted (`ON DELETE SET NULL` on the backend). */
  senderId: string | null;
  type: MessageType;
  body: string;
  /** Set by the server. Do NOT read a timestamp out of `id` for display. */
  createdAt: string;
  /** Client-only: the delivery state of a message you just composed. */
  status?: MessageStatus;
  /** Client-only: the ack's error code when `status === "failed"`. */
  errorCode?: string;
};

/**
 * `ConversationMemberDto` — FLAT, with no nested `UserDto`. Do not reuse
 * `services/auth/types.ts`'s `User` here (it lacks email/emailVerified and has
 * no joinedAt/leftAt).
 */
export type ConversationMember = {
  userId: string;
  role: "member" | "owner";
  /** The public identifier — the way into `GET /users/{username}`, which `userId` is not. */
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
  lastReadMessageId: string | null;
  /**
   * A presence snapshot as of the response, updated afterwards through
   * `presence:changed`. `null` means the endpoint did not compute presence (the
   * conversation list only computes it for DMs) — it does NOT mean offline.
   */
  status: PresenceStatus | null;
  /** Only meaningful while `status === "offline"`. */
  lastSeenAt: string | null;
};

/** `ConversationDto`. Required: id, type, unreadCount, members, createdAt. */
export type Conversation = {
  id: string;
  type: ConversationType;
  /** null for `direct` → the display name comes from the other member. */
  title: string | null;
  lastMessage: Message | null;
  unreadCount: number;
  members: ConversationMember[];
  createdAt: string;
};

/** `ConversationPageDto`. `nextCursor` is a **date-time**. */
export type ConversationPage = {
  items: Conversation[];
  nextCursor: string | null;
};

/**
 * `MessagePageDto`. `items` is **newest first**; `nextCursor` is a **uuid**, and
 * `null` means the history is exhausted (a stop condition, not an error).
 */
export type MessagePage = {
  items: Message[];
  nextCursor: string | null;
};

/** The socket connection state, for `ConnectionBanner`. */
export type ChatConnectionStatus = "connecting" | "online" | "offline";

export type PresenceStatus = "online" | "offline";

export type PresenceEntry = {
  status: PresenceStatus;
  lastSeenAt: string | null;
};
