/**
 * Estimated reading time, computed from `contentText` (plain text generated by
 * the **backend**, §2.3).
 *
 * ⚠️ Usable on the **post page** only. `BlogPostListItem` deliberately carries
 * neither `content` nor `contentText`, so a list of 20 posts does not weigh a
 * few hundred KB; list pages must read the `readingMinutes` the backend returns
 * (§2.3a) — there is no third path.
 *
 * This is the CALCULATION only. The displayed text ("… min read") is
 * user-facing, so it lives at `web.blog.post.readingTime` and is translated at
 * render time — this function knows no locale (`docs/i18n.md` §7.3).
 */
const WORDS_PER_MINUTE = 200;

export function readingMinutes(contentText: string): number {
  const words = contentText.trim().split(/\s+/).filter(Boolean).length;
  // An empty post is still "1 min read": "0 min read" looks like a rendering bug.
  return Math.max(1, Math.round(words / WORDS_PER_MINUTE));
}
